certificate-item:
  type: PAPER
  # Available Placeholders:
  # %winner%, %loser%, %kit%, %arena%, %bet%, %time%
  name: '&bDuel Certificate'
  lore:
  - '&c%loser% &7was defeated by'
  - '&a%winner% &7in a duel with kit &3%kit%'
  - '&7on &f%date%&7.'

# Tutorial: https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
date-format: 'E, dd MMM yyyy HH:mm:ss'